### ISSUE TITLE
Don't read allure.properties

### ISSUE THREAD

**Issue by apanashchenko** [allure-framework/allure-maven-plugin#18] opened 2015-08-20 13:47 UTC
I try add allure.issues.tracker.pattern and allure.tests.management.pattern to allure.properties, but the property doesn't read. Can you investigate this issue please?

**Comment by baev** [comment] 2015-08-20 13:53
@apanashchenko thanks for suggestion. The problem is the maven plugin has the separate classpath, so it can't read the properties from your project resources. I'll think about it

**Comment by apanashchenko** [comment] 2015-08-20 13:57
Thanks a lot. I'll be waiting. Maybe you can give me a hint, how I can set this variable?(mvn site -Dallure.issues.tracker.pattern not good for us, because we use bamboo plugin for report generation)

**Comment by baev** [comment] 2015-08-20 13:58
btw I'll going to add ability to specify the patterns to allure bamboo plugin)

**Comment by apanashchenko** [comment] 2015-08-20 14:00
Cool) waiting for improvements)

**Comment by baev** [comment] 2015-08-20 14:09
You can create a related issue here https://github.com/allure-framework/allure-bamboo-plugin

**Comment by baev** [comment] 2015-08-20 14:10
> Maybe you can give me a hint, how I can set this variable?(mvn site -Dallure.issues.tracker.pattern not good for us

I guess it is the only way for now, so stay turned we are going to fix this

**Comment by baev** [comment] 2015-11-23 17:03
fixed via https://github.com/allure-framework/allure-maven-plugin/pull/23

**Closed by baev** 2015-11-23 17:03 UTC
